### ISSUE TITLE
Switch testing framework to Jest?

### ISSUE THREAD

**Issue by sjhuang26** [codingandcommunity/copilot#17]
Recently I have been considering **switching the testing framework from Jasmine to Jest**. I tried it out today, and I think it works better than the existing framework:
* Jest has much better Typescript support. Configuring it is a breeze, and there were no issues.
* Jest actually gives full error output every time (no strange race condition issues).
* Jest gives better error output (for example, it gives a Git-like diff when the expected and actual strings differ).

I hope switching the framework isn't too big of a difficulty. The syntax is basically identical, and I already have a Jest testing setup working on my machine with all the tests ported over.

I strongly recommend switching to Jest. If you have any questions, let me know. Thanks in advance.

**Comment by koreanwglasses** [comment]
Sounds great! Leave a PR and ill pull it.
